new_strategy_params:
   strategy_id: 8888
   strategy: "LNDU: Peru CCDR"
   strategy_code: "PFLO:PERU_CCDR_PLUR"
   baseline_strategy_id: 0
   Description: "Peru CCDR with partial land use reallocation"
   transformaciones_activas: ["ENTC:TARGET_RENEWABLE_ELEC","ENTC:TARGET_RENEWABLE_ENERGY_PRODUCTION","FGTV:DEC_LEAKS","FGTV:INC_FLARE","INEN:INC_EFFICIENCY_ENERGY","INEN:INC_EFFICIENCY_PRODUCTION","LNDU:DEC_DEFORESTATION","LSMM:INC_CAPTURE_BIOGAS","LSMM:INC_MANAGEMENT_CATTLE_PIGS","LSMM:INC_MANAGEMENT_OTHER","LSMM:INC_MANAGEMENT_POULTRY","LVST:DEC_ENTERIC_FERMENTATION","SCOE:INC_EFFICIENCY_APPLIANCE","TRNS:FUEL_SWITCH_LIGHT_DUTY","TRNS:FUEL_SWITCH_MARITIME","TRNS:FUEL_SWITCH_MEDIUM_DUTY","TRNS:FUEL_SWITCH_RAIL","TRNS:INC_OCCUPANCY","TRNS:MODE_SHIFT_PASSENGER","TRNS:MODE_SHIFT_REGIONAL"]
   strategy_function_name: "pflo_peru_ndc"

ssp_config_params:
   regions: peru
   keys_strategy: 8888,5009
   keys_design: 0
   keys_future: 0
   database_type: csv

tranformation_params:
   energy:
      transformation_trns_electrify_road_light_duty: 1.0
      transformation_trns_electrify_rail: 1.0
      transformation_trns_fuel_switch_road_medium_duty:
      transformation_trns_fuel_switch_maritime: 1.0
      transformation_trns_increase_efficiency_electric: 1.0
      transformation_entc_renewables_target: 1.0
      transformation_scoe_fuel_switch_electrify: 1.0
      transformation_scoe_reduce_heat_energy_demand: 1.0
      transformation_trns_increase_efficiency_non_electric: 1.0
   afolu:
      transformation_lndu_reallocate_land: 0.0
      transformation_lvst_decrease_exports: 1.0
